services:
  spring-project:
    build: .
    container_name: "spring-project111"
    depends_on:
      - database-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database-service:5432/final_project_db
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres123
      - SPRING_HIBERNATE_JPA_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    ports:
      - 8888:8080

  database-service:
    image: 'postgres'
    container_name: 'database-service'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=final_project_db
    ports:
      - 2345:5432